/**
 * Migration invariants — R0 E9.
 *
 * Two things this file enforces that are easy to lose:
 *
 *   1. EVERY TENANT TABLE AND KEY CARRIES THE TENANT.
 *      Asserted independently of the migration that creates them, so a LATER
 *      migration that adds a table without repeating the pattern FAILS rather
 *      than shipping an open table.
 *
 *   2. A DEPLOYED MIGRATION IS IMMUTABLE.
 *      Its checksum is stored. Editing it breaks every existing deployment —
 *      and `create table if not exists` DOES NOT TELL YOU THE NAME IS TAKEN.
 *      The prior attempt had four table names collide silently and had to
 *      prefix seven tables in a later release.
 */

import { test, describe } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { createHash } from 'node:crypto';

const migrationsDir = join(dirname(fileURLToPath(import.meta.url)), '../migrations');
const files = readdirSync(migrationsDir).filter((f) => f.endsWith('.sql')).sort();

/**
 * Checksums of migrations that have been DEPLOYED. Once a migration ships, its
 * entry is added here and never changes.
 *
 * R0 has deployed nothing yet, so this is empty — and that is the honest state.
 */
const DEPLOYED_CHECKSUMS = {
  // '001_catalogue.sql': '<sha256 recorded at first deploy>',
};

describe('migrations', () => {
  test('are numbered, sequential, and have no gaps', () => {
    const numbers = files.map((f) => Number(f.slice(0, 3)));
    numbers.forEach((n, i) => {
      assert.equal(n, i + 1, `expected migration ${i + 1}, found ${n} (${files[i]})`);
    });
  });

  test('a deployed migration has not been edited', () => {
    for (const [file, expected] of Object.entries(DEPLOYED_CHECKSUMS)) {
      const actual = createHash('sha256')
        .update(readFileSync(join(migrationsDir, file)))
        .digest('hex');
      assert.equal(
        actual,
        expected,
        `${file} has been edited after deployment. Every existing deployment stored the old ` +
          `checksum — correct it with a NEW migration instead.`,
      );
    }
  });

  test('every tenant table carries the tenant key', () => {
    // The list of tenant tables is declared, not inferred, so ADDING a tenant table
    // is a deliberate act that shows up in review.
    // Declared, not inferred — ADDING a tenant table is a deliberate act that shows up in review.
    const TENANT_TABLES = ['tenancy_probe'];
    // catalogue_tool is MIXED: global rows carry no facility, local adaptations do.
    // It is checked separately below rather than forced into this list.
    const sql = files.map((f) => readFileSync(join(migrationsDir, f), 'utf8')).join('\n');

    for (const table of TENANT_TABLES) {
      const create = new RegExp(`create table if not exists ${table}\\s*\\(([\\s\\S]*?)\\n\\);`, 'i');
      const match = sql.match(create);
      assert.ok(match, `no create statement found for tenant table ${table}`);
      assert.match(
        match[1],
        /facility_id\s+uuid\s+not null/i,
        `${table} must carry a NOT NULL facility_id — a tenant table without the key is an open table`,
      );
    }
  });

  test('every tenant table has FORCED row-level security, not merely enabled', () => {
    const sql = files.map((f) => readFileSync(join(migrationsDir, f), 'utf8')).join('\n');
    assert.match(
      sql,
      /force row level security/i,
      'enable alone exempts the table owner. It must be FORCED.',
    );
  });

  test('policies are generated by a loop, not hand-written per table', () => {
    const sql = files.map((f) => readFileSync(join(migrationsDir, f), 'utf8')).join('\n');
    assert.match(
      sql,
      /foreach\s+\w+\s+in array/i,
      'A table that gets missed is a table with no isolation, and reviewing twenty ' +
        'near-identical blocks for the one naming the wrong column is HOW a table gets missed.',
    );
  });

  test('the application role is created without superuser or bypass privileges', () => {
    const sql = files.map((f) => readFileSync(join(migrationsDir, f), 'utf8')).join('\n');
    assert.match(sql, /create role checklist_app/i);
    assert.doesNotMatch(sql, /checklist_app[^;]*superuser/i, 'the application role must not be a superuser');
    assert.doesNotMatch(sql, /checklist_app[^;]*bypassrls/i, 'the application role must not bypass RLS');
  });

  test('the application role is granted no DDL and no access to the migration ledger', () => {
    const sql = files.map((f) => readFileSync(join(migrationsDir, f), 'utf8')).join('\n');
    assert.doesNotMatch(sql, /grant\s+all\b[^;]*checklist_app/i, 'grant exactly the data verbs, never ALL');
    assert.doesNotMatch(sql, /grant[^;]*schema_migrations[^;]*checklist_app/i);
  });

  test('catalogue_tool carries a nullable facility — global content is NOT tenant data', () => {
    const sql = files.map((f) => readFileSync(join(migrationsDir, f), 'utf8')).join('\n');
    assert.match(sql, /facility_id\s+uuid,/i,
      'catalogue_tool is mixed: global rows have facility_id NULL, local adaptations carry one. ' +
      'Adding a tenant column to genuinely shared content invites a filter that silently hides it.');
    assert.match(sql, /local_versions_are_facility_scoped/i,
      'a local adaptation must be facility-scoped and global content must not be — enforced by constraint');
  });

  test('★ immutability of a published version is enforced by the DATABASE, not only in code', () => {
    const sql = files.map((f) => readFileSync(join(migrationsDir, f), 'utf8')).join('\n');
    assert.match(sql, /create trigger published_versions_are_immutable/i,
      'A rule enforced only in application code is one forgotten call away from not being enforced.');
    assert.match(sql, /published-version-is-immutable/,
      'the trigger must raise the NAMED refusal, so a test can assert WHICH rule fired');
  });

  test('★ a local adaptation cannot claim its parent authority class', () => {
    const sql = files.map((f) => readFileSync(join(migrationsDir, f), 'utf8')).join('\n');
    assert.match(sql, /adaptation_may_not_claim_parent_authority/i,
      'Adapting class A or B produces class C. A label cannot outrank the content it describes.');
  });

  test('platform operators carry NO facility — the editorial workflow predates identity', () => {
    const sql = files.map((f) => readFileSync(join(migrationsDir, f), 'utf8')).join('\n');
    assert.match(sql, /create table if not exists platform_operator/i);
    assert.doesNotMatch(sql, /platform_operator[\s\S]{0,400}facility_id\s+uuid\s+not null/i,
      'an operator with a facility is a facility member, and belongs to identity-enrolment');
  });

  test('table names do not collide — `create table if not exists` succeeds silently on a taken name', () => {
    const sql = files.map((f) => readFileSync(join(migrationsDir, f), 'utf8')).join('\n');
    const created = [...sql.matchAll(/create table if not exists (\w+)/gi)].map((m) => m[1]);
    const seen = new Set();
    for (const t of created) {
      assert.ok(
        !seen.has(t),
        `${t} is created twice. \`if not exists\` does NOT tell you the name is taken — it ` +
          `silently succeeds and you get the OLD table. Grep the ledger before naming a table.`,
      );
      seen.add(t);
    }
  });
});
